"""Optional Laya-assisted judgments; authority remains with the deterministic system."""

from settings_api.domain.catalogue.lucy.namespace import NAMESPACE
from settings_api.domain.types import OnUnavailable, Origin, SettingDef, SettingType

SETTINGS: tuple[SettingDef, ...] = (
    SettingDef(
        namespace=NAMESPACE,
        key="decisions",
        value_type=SettingType.BOOL,
        default=False,
        conservative_values=(False,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Enable Laya-assisted decisions.",
        description="Off makes no decision calls. On uses the configured decision service.",
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_shadow_mode",
        value_type=SettingType.BOOL,
        default=True,
        conservative_values=(True,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Measure decisions without applying them.",
        description="On records suggestions while preserving ordinary behavior.",
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_capabilities",
        value_type=SettingType.BOOL,
        default=True,
        conservative_values=(True,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Preload relevant available capabilities.",
        description="Only when decisions are enabled. Never executes tools or grants permission.",
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_memory",
        value_type=SettingType.BOOL,
        default=True,
        conservative_values=(True,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Rank trusted memory topics by relevance.",
        description="Only when decisions are enabled. Incognito sends no memories.",
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_recovery",
        value_type=SettingType.BOOL,
        default=False,
        conservative_values=(False,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Suggest a new approach after repeated failures.",
        description="Advisory only. Existing loop limits and approvals remain in force.",
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_claims",
        value_type=SettingType.BOOL,
        default=True,
        conservative_values=(True,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Catch a reply that claims work no step did, in any wording.",
        description=("Only when decisions are enabled. Otherwise replies go out unchecked."),
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_timeout_ms",
        value_type=SettingType.INT,
        default=1000,
        minimum=50,
        maximum=5000,
        operator_clampable=True,
        conservative_values=(1000,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Maximum wait for one decision in milliseconds.",
        description="Exhaustion uses ordinary behavior; helpers do not call the decision service.",
    ),
    SettingDef(
        namespace=NAMESPACE,
        key="decision_max_per_turn",
        value_type=SettingType.INT,
        default=8,
        minimum=1,
        maximum=32,
        operator_clampable=True,
        conservative_values=(8,),
        on_unavailable=OnUnavailable.USE_DEFAULT,
        origin=Origin.EXISTING,
        origin_note="Consumed by the hub's per-turn decisions policy.",
        summary="Maximum decision calls in one main turn.",
        description="Exhaustion uses ordinary behavior; helpers do not call the decision service.",
    ),
)
