"""Regenerate ``docs/catalogue.md`` from the catalogue modules.

The generated page is the one a person reads to find out what this service can be told,
and the one an author of a consuming service reads to find out what their namespace
offers. It is generated rather than written because a hand-maintained copy of a table is
a copy that drifts, and the drift is invisible: nobody diffs prose against code.

A test asserts the checked-in file matches what this produces, so a catalogue change with
no ``make catalogue`` is a failing build rather than a stale page.
"""

from __future__ import annotations

from pathlib import Path

from settings_api.domain.registry import CATALOGUE
from settings_api.domain.types import OnUnavailable, Origin, SettingDef, SettingType

DOCS = Path(__file__).resolve().parent.parent / "docs" / "catalogue.md"

HEADER = """# The catalogue

Every setting this build of settings-api knows about. **Generated by `make catalogue`** --
edit `src/settings_api/domain/catalogue/` and regenerate; do not edit this file.

Read this alongside [integration.md](integration.md), which says how a service consumes a
namespace, and [adding-a-service.md](adding-a-service.md), which says how a new one gets
its own.

## How to read an entry

**Bounds** are the catalogue's. A deployment's operator policy may narrow them further, and
`describe_settings` reports the narrowed ones -- so the bounds a *write* is checked against
are the ones that endpoint returns, not necessarily the ones here.

**On unavailable** says what a consuming service must do when settings-api cannot be
reached. `use default` means the default is the most conservative value this setting has,
so landing on it cannot weaken anything the person asked for. `refuse` means it is not:
the default is permissive because the service needs it to be, so falling back would
override an explicit restriction and the operation must fail instead. The field has no
default in the code, because choosing between them is the decision the author has to make
and getting it wrong is silent.

**Origin** says whether wiring the setting up is a change at a call site or a change to the
owning service. `existing` means that service already has the knob, deployment-wide, and
`origin` names it. `proposed` means **the setting does nothing until that service changes**,
and the note says what the change is. Nothing here ships a setting that silently does
nothing without saying so.

**Owner only** marks the settings a consuming service may not write even while holding the
person's own token. There are two, and both are ones where the service that would benefit
from changing them is the service that should not be allowed to.
"""


def _bounds(entry: SettingDef) -> str:
    """Render an entry's bounds as one cell."""
    parts: list[str] = []
    if entry.value_type is SettingType.ENUM:
        parts.append(" / ".join(f"`{choice}`" for choice in entry.choices))
    if entry.minimum is not None or entry.maximum is not None:
        low = "" if entry.minimum is None else str(entry.minimum)
        high = "" if entry.maximum is None else str(entry.maximum)
        parts.append(f"{low}-{high}")
    if entry.max_chars is not None:
        parts.append(f"≤{entry.max_chars} chars")
    if entry.pattern is not None:
        parts.append(f"`{entry.pattern}`")
    if entry.max_items is not None:
        parts.append(f"≤{entry.max_items} items")
    if entry.max_item_chars is not None:
        parts.append(f"items ≤{entry.max_item_chars} chars")
    if entry.extra_check.value != "none":
        parts.append(f"must resolve as a {entry.extra_check.value}")
    if entry.nullable:
        parts.append("nullable")
    if entry.operator_clampable:
        parts.append("operator-clampable")
    return ", ".join(parts) or "—"


def _default(entry: SettingDef) -> str:
    if entry.default is None:
        return "`null`"
    if isinstance(entry.default, bool):
        return f"`{str(entry.default).lower()}`"
    if isinstance(entry.default, list):
        return "`[]`" if not entry.default else f"`{entry.default}`"
    return f"`{entry.default}`"


def _flags(entry: SettingDef) -> str:
    flags: list[str] = []
    if entry.owner_writable_only:
        flags.append("**owner only**")
    if entry.deprecated_by is not None:
        flags.append(f"deprecated by `{entry.deprecated_by}`")
    if entry.retired_at is not None:
        flags.append(f"retired {entry.retired_at}")
    return " · ".join(flags)


def _entry_section(entry: SettingDef) -> str:
    """One entry, as a heading, a table row and its prose."""
    fallback = "use default" if entry.on_unavailable is OnUnavailable.USE_DEFAULT else "**refuse**"
    origin = "existing" if entry.origin is Origin.EXISTING else "**proposed**"
    lines = [
        f"#### `{entry.qualified}`",
        "",
        f"*{entry.summary}*",
        "",
        "| | |",
        "| --- | --- |",
        f"| Type | `{entry.value_type.value}` |",
        f"| Default | {_default(entry)} |",
        f"| Bounds | {_bounds(entry)} |",
        f"| On unavailable | {fallback} |",
        f"| Origin | {origin} — {entry.origin_note} |",
    ]
    if entry.conservative_values:
        safe = ", ".join(_literal(value) for value in entry.conservative_values)
        lines.append(f"| Safe to fall back to | {safe} |")
    flags = _flags(entry)
    if flags:
        lines.append(f"| Flags | {flags} |")
    lines.extend(["", entry.description, ""])
    return "\n".join(lines)


def _literal(value: object) -> str:
    if value is None:
        return "`null`"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, list):
        return "`[]`" if not value else f"`{value}`"
    return f"`{value}`"


def render() -> str:
    """The whole page."""
    total = sum(len(entries) for entries in CATALOGUE.values())
    parts = [
        HEADER,
        "",
        f"**{total} settings across {len(CATALOGUE)} namespaces.**",
        "",
        "## Contents",
        "",
    ]
    for namespace, entries in CATALOGUE.items():
        names = ", ".join(f"`{entry.key}`" for entry in entries)
        parts.append(f"- **`{namespace}`** ({len(entries)}) — {names}")
    parts.append("")

    for namespace, entries in CATALOGUE.items():
        parts.append(f"## `{namespace}`")
        parts.append("")
        module_doc = _module_doc(namespace)
        if module_doc:
            parts.extend([module_doc, ""])
        proposed = [entry for entry in entries if entry.origin is Origin.PROPOSED]
        if proposed:
            names = ", ".join(f"`{entry.key}`" for entry in proposed)
            parts.append(
                f"> **Needs a change in the owning service first:** {names}. Until that "
                "change lands, setting these stores the value and changes no behaviour."
            )
            parts.append("")
        parts.extend(_entry_section(entry) for entry in entries)
    return "\n".join(parts).rstrip() + "\n"


def _module_doc(namespace: str) -> str:
    """The namespace module's own docstring, which says why the namespace looks like it does."""
    module = __import__(f"settings_api.domain.catalogue.{namespace}", fromlist=["__doc__"])
    doc = module.__doc__ or ""
    lines = doc.strip().splitlines()
    # The first line is a title in the module; the page already has one.
    return "\n".join(lines[1:]).strip()


def main() -> None:
    DOCS.write_text(render())
    print(f"wrote {DOCS}")


if __name__ == "__main__":
    main()
